--CREATE DATABASE MAIN
--DROP DATABASE MAIN
--ALTER DATABASE main MODIFY NAME= son
--USE son
CREATE DATABASE SALES
ON
(
NAME = SALE_DATA,
FILENAME ='D:\DATABASE\SALES.MDF',
SIZE = 10MB,
MAXSIZE = 50MB,
FILEGROWTH = 5MB
)
LOG ON
(
NAME = SALE_LOG,
FILENAME ='D:\DATABASE\SALES.LDF',
SIZE = 10MB,
MAXSIZE = 50MB,
FILEGROWTH = 5MB

)